package es.iobuilder.tokenizer.authservice.infrastructure.db.model;

import lombok.Builder;
import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;


/**
 * User DBO Entity
 */
@Entity
@Data
@Builder
public class UserEntity {

    /**
     * Id. Autogenerated
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * User's name
     */
    private String name;

    /**
     * User's Password
     */
    private String password;

    /**
     * user's Email
     */
    private String email;

    /**
     * User's phone Number
     */
    private String phone;
}
